// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wow.Infra.Data.Context;

namespace Wow.Infra.Data.Migrations
{
    [DbContext(typeof(TesteWowContext))]
    [Migration("20190716144107_InitMigration")]
    partial class InitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wow.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<bool>("Blocked");

                    b.Property<string>("HolderAccountName")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<double>("ValueBalance");

                    b.Property<double>("ValueLimit");

                    b.HasKey("Guid");

                    b.ToTable("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
